print ('==== DESAFIO 02 =====')
print ('Digite apenas numeros no formato DD/MM/AAA')
dia = input ('Em qual dia você nasceu? ')
mes = input ('Em qual mês você nasceu? ')
ano = input ('Em qual ano você nasceu? ')
print ('Você nasceu no dia', dia, '/', mes, '/', ano)
