n = (input('Escreva algo:'))
print('Informações sobre: {}'.format(n))
print('O tipo primitivo desse valor é', type(n))
print('Numérico?', n.isnumeric())
print('Alfabético?', n.isalpha())
print('Alfa Numérico?', n.isalnum())
print('Decimal?', n.isdecimal())
print('Tudo Minúsculo?', n.islower())
print('Tudo Maiúsculo?', n.isupper())
print('Só tem espaços?', n.isspace())
print('Esta Capitalizada?', n.istitle())
